version: '3.8'

services:
  flutter-assistant:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"  # API port
      - "${SSL_PORT:-8443}:${SSL_PORT:-8443}"  # HTTPS/WSS port
      - "${FLUTTER_WEB_PORT:-8080}:${FLUTTER_WEB_PORT:-8080}"  # Web server port for Flutter previews
    volumes:
      - ../integration:/app/integration  # Mount integration directory
      - ../output:/app/output  # Mount output directory
      - ../ssl:/app/ssl  # Mount SSL certificates directory
    env_file:
      - ../.env
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-pro}
      - WEB_HOST=${WEB_HOST:-0.0.0.0}  # Bind to all interfaces
      - PUBLIC_HOST=${PUBLIC_HOST:-localhost}  # Public IP for URLs returned to clients
      - FLUTTER_WEB_PORT=${FLUTTER_WEB_PORT:-8080}
      - WEB_PORT=${WEB_PORT:-8080}
      - API_PORT=${API_PORT:-8000}
      - COMMAND_TIMEOUT=${COMMAND_TIMEOUT:-600}
      - BUILD_TIMEOUT=${BUILD_TIMEOUT:-6000}
      - ENABLE_SSL=${ENABLE_SSL:-true}  # Enable SSL support
      - SSL_CERT_FILE=${SSL_CERT_FILE:-/app/ssl/cert.pem}
      - SSL_KEY_FILE=${SSL_KEY_FILE:-/app/ssl/key.pem}
      - SSL_PORT=${SSL_PORT:-8443}  # HTTPS/WSS port
    restart: unless-stopped 